export default {
	colorPrimary: '#F02475',
	colorOnPrimary: '#FFFFFF',
	colorPrimaryContainer: '#BD1C5C',
	colorOnPrimaryContainer: '#FFFFFF',
	colorSecondary: '#F02475',
	colorOnSecondary: '#FFFFFF',
	colorSecondaryContainer: '#F02475',
	colorOnSecondaryContainer: '#FFFFFF',
	colorTertiary: '#55971C',
	colorOnTertiary: '#FFFFFF',
	colorTertiaryContainer: '#386412',
	colorOnTertiaryContainer: '#E5E1E5',
	colorBackground: '#16151D',
	colorOnBackground: '#E5E1E5',
	colorSurface: '#16151D',
	colorOnSurface: '#E5E1E5',
	colorSurfaceVariant: '#524346',
	colorOnSurfaceVariant: '#D6C1C4',
	colorOutline: '#9F8C8F',
	colorOnSurfaceInverse: '#FFFFFF',
	colorSurfaceInverse: '#333043',
	colorPrimaryInverse: '#F02475',
	elevationOverlayColor: '#2C0013',
};
