export default {
	colorPrimary: '#FFB2B9',
	colorOnPrimary: '#67001B',
	colorPrimaryContainer: '#91002A',
	colorOnPrimaryContainer: '#FFDADD',
	colorSecondary: '#FFB2B9',
	colorOnSecondary: '#67001B',
	colorSecondaryContainer: '#91002A',
	colorOnSecondaryContainer: '#FFDADD',
	colorTertiary: '#E8C08E',
	colorOnTertiary: '#432C06',
	colorTertiaryContainer: '#5D421B',
	colorOnTertiaryContainer: '#FFDDB1',
	colorBackground: '#201A1A',
	colorOnBackground: '#ECDFDF',
	colorSurface: '#201A1A',
	colorOnSurface: '#ECDFDF',
	colorSurfaceVariant: '#534344',
	colorOnSurfaceVariant: '#D7C1C2',
	colorOutline: '#A08C8D',
	colorOnSurfaceInverse: '#201A1A',
	colorSurfaceInverse: '#ECDFDF',
	colorPrimaryInverse: '#B61E40',
};
