export default {
  colorPrimary: "#5ed4fc",
  colorOnPrimary: "#003544",
  colorPrimaryContainer: "#004d61",
  colorOnPrimaryContainer: "#b8eaff",
  colorSecondary: "#5ed4fc",
  colorOnSecondary: "#003544",
  colorSecondaryContainer: "#004d61",
  colorOnSecondaryContainer: "#b8eaff",
  colorTertiary: "#92f7bc",
  colorOnTertiary: "#001c3b",
  colorTertiaryContainer: "#c3fada",
  colorOnTertiaryContainer: "#78ffd6",
  colorBackground: "#001c3b",
  colorOnBackground: "#d5e3ff",
  colorSurface: "#001c3b",
  colorOnSurface: "#d5e3ff",
  colorSurfaceVariant: "#40484c",
  colorOnSurfaceVariant: "#bfc8cc",
  colorOutline: "#8a9296",
  colorOnSurfaceInverse: "#001c3b",
  colorSurfaceInverse: "#ffe3c4",
  colorPrimaryInverse: "#a12b03"
}