export default {
	colorPrimary: '#FFFFFF',
	colorOnPrimary: '#5A5A5A',
	colorPrimaryContainer: '#FFFFFF',
	colorOnPrimaryContainer: '#000000',
	colorSecondary: '#FFFFFF',
	colorOnSecondary: '#5A5A5A',
	colorSecondaryContainer: '#717171',
	colorOnSecondaryContainer: '#E4E4E4',
	colorTertiary: '#000000',
	colorOnTertiary: '#FFFFFF',
	colorTertiaryContainer: '#00419E',
	colorOnTertiaryContainer: '#D8E2FF',
	colorBackground: '#1E1E1E',
	colorOnBackground: '#E6E6E6',
	colorSurface: '#1E1E1E',
	colorOnSurface: '#E6E6E6',
	colorSurfaceVariant: '#4E4E4E',
	colorOnSurfaceVariant: '#D1D1D1',
	colorOutline: '#999999',
	colorOnSurfaceInverse: '#1E1E1E',
	colorSurfaceInverse: '#E6E6E6',
	colorPrimaryInverse: '#CECECE',
};
