export default {
	colorPrimary: '#006D2F',
	colorOnPrimary: '#FFFFFF',
	colorPrimaryContainer: '#96F8A9',
	colorOnPrimaryContainer: '#002109',
	colorSecondary: '#006D2F',
	colorOnSecondary: '#FFFFFF',
	colorSecondaryContainer: '#96F8A9',
	colorOnSecondaryContainer: '#002109',
	colorTertiary: '#B91D22',
	colorOnTertiary: '#FFFFFF',
	colorTertiaryContainer: '#FFDAD5',
	colorOnTertiaryContainer: '#410003',
	colorBackground: '#FBFDF7',
	colorOnBackground: '#1A1C19',
	colorSurface: '#FBFDF7',
	colorOnSurface: '#1A1C19',
	colorSurfaceVariant: '#DDE5DA',
	colorOnSurfaceVariant: '#414941',
	colorOutline: '#717970',
	colorOnSurfaceInverse: '#F0F2EC',
	colorSurfaceInverse: '#2F312E',
	colorPrimaryInverse: '#7ADB8F',
};
