export default {
	colorPrimary: '#7B46AF',
	colorOnPrimary: '#EDE2FF',
	colorPrimaryContainer: '#7B46AF',
	colorOnPrimaryContainer: '#EDE2FF',
	colorSecondary: '#7B46AF',
	colorOnSecondary: '#EDE2FF',
	colorSecondaryContainer: '#7B46AF',
	colorOnSecondaryContainer: '#EDE2FF',
	colorTertiary: '#EDE2FF',
	colorOnTertiary: '#7B46AF',
	colorTertiaryContainer: '#EDE2FF',
	colorOnTertiaryContainer: '#7B46AF',
	colorBackground: '#EDE2FF',
	colorOnBackground: '#1B1B22',
	colorSurface: '#EDE2FF',
	colorOnSurface: '#1B1B22',
	colorSurfaceVariant: '#B9B0CC',
	colorOnSurfaceVariant: '#D849454E',
	colorOutline: '#7B46AF',
	colorOnSurfaceInverse: '#F3EFF4',
	colorSurfaceInverse: '#313033',
	colorPrimaryInverse: '#D6BAFF',
	elevationOverlayColor: '#7B46AF',
};
