export default {
  colorPrimary: "#BB0054",
  colorOnPrimary: "#FFFFFF",
  colorPrimaryContainer: "#FFD9E1",
  colorOnPrimaryContainer: "#3F0017",
  colorSecondary: "#BB0054",
  colorOnSecondary: "#FFFFFF",
  colorSecondaryContainer: "#FFD9E1",
  colorOnSecondaryContainer: "#3F0017",
  colorTertiary: "#006638",
  colorOnTertiary: "#FFFFFF",
  colorTertiaryContainer: "#00894b",
  colorOnTertiaryContainer: "#2D1600",
  colorBackground: "#FFFBFF",
  colorOnBackground: "#1C1B1F",
  colorSurface: "#FFFBFF",
  colorOnSurface: "#1C1B1F",
  colorSurfaceVariant: "#F3DDE0",
  colorOnSurfaceVariant: "#524346",
  colorOutline: "#847376",
  colorOnSurfaceInverse: "#F4F0F4",
  colorSurfaceInverse: "#313033",
  colorPrimaryInverse: "#FFB1C4",
  elevationOverlayColor: "#BB0054"
}