export default {
  colorPrimary: "#B61E40",
  colorOnPrimary: "#FFFFFF",
  colorPrimaryContainer: "#FFDADD",
  colorOnPrimaryContainer: "#40000D",
  colorSecondary: "#B61E40",
  colorOnSecondary: "#FFFFFF",
  colorSecondaryContainer: "#FFDADD",
  colorOnSecondaryContainer: "#40000D",
  colorTertiary: "#775930",
  colorOnTertiary: "#FFFFFF",
  colorTertiaryContainer: "#FFDDB1",
  colorOnTertiaryContainer: "#2A1800",
  colorBackground: "#FCFCFC",
  colorOnBackground: "#201A1A",
  colorSurface: "#FCFCFC",
  colorOnSurface: "#201A1A",
  colorSurfaceVariant: "#F4DDDD",
  colorOnSurfaceVariant: "#534344",
  colorOutline: "#857374",
  colorOnSurfaceInverse: "#FBEDED",
  colorSurfaceInverse: "#362F2F",
  colorPrimaryInverse: "#FFB2B9"
}