export default {
  colorPrimary: "#008080",
  colorOnPrimary: "#FFFFFF",
  colorPrimaryContainer: "#008080",
  colorOnPrimaryContainer: "#FFFFFF",
  colorSecondary: "#008080",
  colorOnSecondary: "#FFFFFF",
  colorSecondaryContainer: "#BFDFDF",
  colorOnSecondaryContainer: "#008080",
  colorTertiary: "#FF7F7F",
  colorOnTertiary: "#000000",
  colorTertiaryContainer: "#2A1616",
  colorOnTertiaryContainer: "#FF7F7F",
  colorBackground: "#FAFAFA",
  colorOnBackground: "#050505",
  colorSurface: "#FAFAFA",
  colorOnSurface: "#050505",
  colorSurfaceVariant: "#DAE5E2",
  colorOnSurfaceVariant: "#050505",
  colorOutline: "#6F7977",
  colorOnSurfaceInverse: "#FAFAFA",
  colorSurfaceInverse: "#050505",
  colorPrimaryInverse: "#40E0D0",
  colorError: "#FF7F7F",
  colorOnError: "#000000",
  elevationOverlayColor: "#BFDFDF"
}