export default {
  colorPrimary: "#006780",
  colorOnPrimary: "#ffffff",
  colorPrimaryContainer: "#B4D4DF",
  colorOnPrimaryContainer: "#001f28",
  colorSecondary: "#006780",
  colorOnSecondary: "#ffffff",
  colorSecondaryContainer: "#b8eaff",
  colorOnSecondaryContainer: "#001f28",
  colorTertiary: "#92f7bc",
  colorOnTertiary: "#001c3b",
  colorTertiaryContainer: "#c3fada",
  colorOnTertiaryContainer: "#78ffd6",
  colorBackground: "#fdfbff",
  colorOnBackground: "#001c3b",
  colorSurface: "#fdfbff",
  colorOnSurface: "#001c3b",
  colorSurfaceVariant: "#dce4e8",
  colorOnSurfaceVariant: "#40484c",
  colorOutline: "#70787c",
  colorOnSurfaceInverse: "#ffe3c4",
  colorSurfaceInverse: "#020400",
  colorPrimaryInverse: "#ff987f"
}