export default {
  colorPrimary: "#000000",
  colorOnPrimary: "#FFFFFF",
  colorPrimaryContainer: "#000000",
  colorOnPrimaryContainer: "#FFFFFF",
  colorSecondary: "#000000",
  colorOnSecondary: "#FFFFFF",
  colorSecondaryContainer: "#DDDDDD",
  colorOnSecondaryContainer: "#0C0C0C",
  colorTertiary: "#FFFFFF",
  colorOnTertiary: "#000000",
  colorTertiaryContainer: "#D8E2FF",
  colorOnTertiaryContainer: "#001947",
  colorBackground: "#FDFDFD",
  colorOnBackground: "#222222",
  colorSurface: "#FDFDFD",
  colorOnSurface: "#222222",
  colorSurfaceVariant: "#EDEDED",
  colorOnSurfaceVariant: "#515151",
  colorOutline: "#838383",
  colorOnSurfaceInverse: "#F4F4F4",
  colorSurfaceInverse: "#333333",
  colorPrimaryInverse: "#A6A6A6"
}