export default {
  colorPrimary: "#AE3200",
  colorOnPrimary: "#FFFFFF",
  colorPrimaryContainer: "#FFDBCF",
  colorOnPrimaryContainer: "#3B0A00",
  colorSecondary: "#AE3200",
  colorOnSecondary: "#FFFFFF",
  colorSecondaryContainer: "#FFDBCF",
  colorOnSecondaryContainer: "#3B0A00",
  colorTertiary: "#6B5E2F",
  colorOnTertiary: "#FFFFFF",
  colorTertiaryContainer: "#F5E2A7",
  colorOnTertiaryContainer: "#231B00",
  colorBackground: "#FCFCFC",
  colorOnBackground: "#211A18",
  colorSurface: "#FCFCFC",
  colorOnSurface: "#211A18",
  colorSurfaceVariant: "#F5DED8",
  colorOnSurfaceVariant: "#53433F",
  colorOutline: "#85736E",
  colorOnSurfaceInverse: "#FBEEEB",
  colorSurfaceInverse: "#362F2D",
  colorPrimaryInverse: "#FFB59D"
}